# Welcome to Jekyll!

# Website settings
title: "dgmouris  "
description: "Dan Mouris's blog on technical things"
keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://dgmouris.com"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://dgmouris.com/static/img/blog'

# author
author:
  name: 'Dan'
  first_name: 'Daniel'
  last_name: 'Mouris'
  email: 'dgmouris@gmail.com'
  facebook_username: 'daniel.mouris'
  github_username: 'dgmouris'
  head_img: 'static/img/landing/profile.jpg'
  linkedin_username: 'daniel-mouris-baa4b972'
# social link
dgmouris:
  first_name: 'Daniel'
  last_name: 'Mouris'
  description: 'Programming enthusiast and animal lover.'
  link: 'http://dgmouris.com'
  email: 'dgmouris@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Contact'

# # my projects
# project:
#   saplatform:
#     name: 'Saplatform'
#     url: '/Jack614/saplatform'
#     img: 'static/img/landing/saplatform.png'
#   jalpc:
#     name: 'Jalpc'
#     url: '/Jack614/jalpc_jekyll_theme'
#     img: 'static/img/landing/jekyll.png'
#   angularjs:
#     name: 'Jalpc-A'
#     url: '/Jack614/Jalpc-A'
#     img: 'static/img/landing/angularjs.png'
#   Rsser:
#     name: 'Rsser'
#     url: '/Jack614/Rsser'
#     img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  blog: 'Blog'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-83644649-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
